// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA9xmqDM8K3ieab_H8QrRc3P5gGHsCDpXM',
    appId: '1:1028357061619:android:48434206b3ff846778f086',
    messagingSenderId: '1028357061619',
    projectId: 'iqra-network-dev',
    databaseURL: 'https://iqra-network-dev.firebaseio.com',
    storageBucket: 'iqra-network-dev.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC8_tBk57onxfokmmxoqkr4L3IqSrUgG80',
    appId: '1:1028357061619:ios:51f050b7ea22b48778f086',
    messagingSenderId: '1028357061619',
    projectId: 'iqra-network-dev',
    databaseURL: 'https://iqra-network-dev.firebaseio.com',
    storageBucket: 'iqra-network-dev.appspot.com',
    androidClientId: '1028357061619-h0uiqhviprgdgpogfqm65jjonlo6ddi6.apps.googleusercontent.com',
    iosClientId: '1028357061619-cgkdqtlv7f3jtionlfdnhudpta8pus8k.apps.googleusercontent.com',
    iosBundleId: 'com.example.iqra',
  );
}
