// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAog80OtNZmi32bv_pEAndrzqNsq-HTaA0',
    appId: '1:375631617862:android:9e6f211caeacd85633cf47',
    messagingSenderId: '375631617862',
    projectId: 'iqra-network',
    databaseURL: 'https://iqra-network.firebaseio.com',
    storageBucket: 'iqra-network.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBdPO5etT23ZasVwiwbU7T00cXqRoiyZwY',
    appId: '1:375631617862:ios:6b717b5110319eae33cf47',
    messagingSenderId: '375631617862',
    projectId: 'iqra-network',
    databaseURL: 'https://iqra-network.firebaseio.com',
    storageBucket: 'iqra-network.appspot.com',
    iosClientId: '375631617862-jbclobfnkhc4b4k1v4jthv3041486ujo.apps.googleusercontent.com',
    iosBundleId: 'com.iqranetwork.dashboard',
  );
}
